# [[scripts_downstream/04_visualization.R]]
# Goal: Generate PCA, Volcano, and Heatmap plots for MiaPAca-2 results.

library(DESeq2)
library(ggplot2)
library(EnhancedVolcano)
library(ggVennDiagram)
library(ComplexHeatmap)
library(circlize)
library(tidyverse)
library(org.Hs.eg.db)
library(clusterProfiler)
library(enrichplot)
library(patchwork)

# 1. Load data
# Uses the .RData generated by previous steps
load("./.RData/02_deseq_results.RData")
load("./.RData/03_enrichment_results.RData")

# 1.5 ID Mapping (ENSG -> Symbol)
message("Mapping gene IDs...")
gene_ids <- rownames(dds)
gene_map <- bitr(gene_ids, fromType = "ENSEMBL", toType = "SYMBOL", OrgDb = org.Hs.eg.db) %>%
  distinct(ENSEMBL, .keep_all = TRUE)
row.names(gene_map) <- gene_map$ENSEMBL

# Ensure output directories exist
dir.create("../results/figures", showWarnings = FALSE, recursive = TRUE)

# Transform counts (VST)
vsd <- vst(dds, blind=FALSE)

# 1.6 Create clean Sample Names for display
# Combine Conc. and Replicate to get names like "DMSO_1" or "0.5nM_1"
colData(vsd)$display_name <- paste0(colData(vsd)$Conc., "_", colData(vsd)$Replicate)
colnames(vsd) <- colData(vsd)$display_name

# Order VSD columns by condition (DMSO -> 0.5 -> 1 -> 5)
vsd <- vsd[, order(vsd$condition)]

# Shared dose colour palette (reused across PCA + heatmaps)
cond_levels   <- unique(as.character(colData(vsd)$condition))
dose_palette_shared <- setNames(
  colorRampPalette(RColorBrewer::brewer.pal(min(length(cond_levels), 8), "Set2"))(length(cond_levels)),
  cond_levels
)

p_pca <- plotPCA(vsd, intgroup = "condition") +
  scale_color_manual(values = dose_palette_shared) +
  theme_classic() +
  theme(
    panel.background  = element_rect(fill = "white", color = NA),
    plot.background   = element_rect(fill = "white", color = NA),
    panel.grid.major  = element_line(color = "grey88", linewidth = 0.4),
    panel.grid.minor  = element_line(color = "grey93", linewidth = 0.2)
  ) +
  ggtitle("PCA Plot: MiaPAca-2 Drug Response")

ggsave("../results/figures/04_pca_plot.png", p_pca, width = 8, height = 6, bg = "white")
message("[OK] PCA plot saved -> 04_pca_plot.png  (8x6 in, ", length(cond_levels), " conditions)")

# 3. Multi-dose Volcano Plots -- individual per dose + stitched combined
# Loop through contrasts for all doses
volcano_plots <- list()
for (dose in names(results_list)) {
  message("Generating Volcano for ", dose)
  res_shrunk <- results_list[[dose]]$shrunk
  safe_name <- str_replace_all(dose, "[^a-zA-Z0-9]", "_")
  
  # Map ENSG IDs to Gene Symbols for labels
  ensg_ids <- rownames(res_shrunk)
  sym_labels <- gene_map[ensg_ids, "SYMBOL"]
  sym_labels <- ifelse(is.na(sym_labels), ensg_ids, sym_labels) # fallback to ENSG
  
  # Direction-based custom coloring: Red=Up, Blue=Down, Grey=Not Significant
  res_df <- as.data.frame(res_shrunk)
  pCut <- 0.05; fcCut <- 1.0
  keyvals <- case_when(
    res_df$log2FoldChange >  fcCut & !is.na(res_df$padj) & res_df$padj < pCut ~ "#D62728",
    res_df$log2FoldChange < -fcCut & !is.na(res_df$padj) & res_df$padj < pCut ~ "#1F77B4",
    TRUE ~ "grey60"
  )
  names(keyvals) <- case_when(
    keyvals == "#D62728" ~ "Upregulated",
    keyvals == "#1F77B4" ~ "Downregulated",
    TRUE ~ "Not Significant"
  )
  
  # Gene count summary for subtitle
  n_up   <- sum(keyvals == "#D62728", na.rm = TRUE)
  n_down <- sum(keyvals == "#1F77B4", na.rm = TRUE)
  n_ns   <- sum(keyvals == "grey60",  na.rm = TRUE)
  count_subtitle <- paste0("Up: ", n_up, "  |  Down: ", n_down, "  |  Not Significant: ", n_ns)
  
  p_volcano <- EnhancedVolcano(res_shrunk,
                               lab = sym_labels,
                               x = 'log2FoldChange',
                               y = 'padj',
                               title = paste(dose, 'vs DMSO'),
                               subtitle = count_subtitle,
                               ylab = "-log10(Adjusted p-value)",
                               pCutoff = pCut,
                               FCcutoff = fcCut,
                               colCustom = keyvals,
                               colAlpha = 0.8)
  
  volcano_plots[[dose]] <- p_volcano
  out_vol <- paste0("../results/figures/04_volcano_", safe_name, ".png")
  ggsave(out_vol, p_volcano, width = 10, height = 8, bg = "white")
  message("[OK] Volcano saved  -> 04_volcano_", safe_name, ".png",
          "  |  Up: ", n_up, "  Down: ", n_down, "  NS: ", n_ns)
}

# Stitch all volcano plots side-by-side
if (length(volcano_plots) > 1) {
  combined_volcano <- wrap_plots(volcano_plots, nrow = 1) +
    plot_annotation(
      title = "Volcano Plots: All Concentrations vs DMSO",
      theme = theme(plot.title = element_text(face = "bold", hjust = 0.5))
    )
  ggsave("../results/figures/04_volcano_combined.png",
         combined_volcano, width = 10 * length(volcano_plots), height = 9, bg = "white")
  message("[OK] Combined volcano -> 04_volcano_combined.png",
          "  (", length(volcano_plots), " panels, ", 10 * length(volcano_plots), "x9 in)")
}

# 4. Venn Diagram (3.1a)
# Extract significant gene sets for each dose
sig_list <- lapply(results_list, function(x) {
  rownames(subset(as.data.frame(x$shrunk), padj < 0.05 & abs(log2FoldChange) > 1))
})

# Filter out empty sets if any
sig_list <- sig_list[sapply(sig_list, length) > 0]

if (length(sig_list) >= 2) {
  p_venn <- ggVennDiagram(sig_list) +
    scale_fill_gradient(low = "white", high = "red") +
    ggtitle("Overlap of DEGs across Kromastat Doses")
  
  ggsave("../results/figures/04_venn_diagram_doses.png", p_venn,
         width = 8, height = 8, bg = "white")
  message("[OK] Venn diagram  -> 04_venn_diagram_doses.png",
          "  (", length(sig_list), " dose sets)")
}

# 5. Pathway-specific Heatmap
top_go <- enrichment_results_all[["5nM"]]$ora_go
if (!is.null(top_go)) {
  top_pathways <- top_go@result %>%
    filter(p.adjust < 0.05) %>%
    head(6)

  expanded_matrix_list <- list()
  annotation_row_list  <- list()

  for (i in seq_len(nrow(top_pathways))) {
    path_name  <- top_pathways$Description[i]
    safe_path  <- str_trunc(str_replace_all(path_name, "[^a-zA-Z0-9]", "_"), 30)
    genes_path <- str_split(top_pathways$geneID[i], "/")[[1]]
    genes_path <- intersect(genes_path, rownames(vsd))
    message("Pathway '", path_name, "': ", length(genes_path), " genes found in VSD.")

    if (length(genes_path) > 0) {
      mat_slice <- assay(vsd)[genes_path, , drop = FALSE]
      rownames(mat_slice) <- paste0(genes_path, "__", safe_path)
      expanded_matrix_list[[path_name]] <- mat_slice
      annot_slice <- data.frame(Pathway = rep(path_name, length(genes_path)))
      rownames(annot_slice) <- rownames(mat_slice)
      annotation_row_list[[path_name]] <- annot_slice
    }
  }

  if (length(expanded_matrix_list) > 0) {
    mat_pathway  <- do.call(rbind, expanded_matrix_list)
    df_annot_row <- do.call(rbind, annotation_row_list)
    mat_pathway  <- mat_pathway - rowMeans(mat_pathway)
    mat_pathway  <- pmin(pmax(mat_pathway, -2), 2)

    orig_ensg       <- str_split_i(rownames(mat_pathway), "__", 1)
    symbols_display <- gene_map[orig_ensg, "SYMBOL"]
    labels_display  <- ifelse(is.na(symbols_display), orig_ensg, symbols_display)

    wrapped_pw     <- str_wrap(df_annot_row$Pathway, width = 20)
    pathway_factor <- factor(wrapped_pw, levels = unique(wrapped_pw))

    col_fun <- colorRamp2(c(-2, 0, 2), c("navy", "white", "firebrick3"))

    pathway_names <- levels(pathway_factor)
    n_pw          <- length(pathway_names)
    pw_palette    <- setNames(
      colorRampPalette(RColorBrewer::brewer.pal(min(n_pw, 8), "Set1"))(n_pw),
      pathway_names
    )

    conditions   <- colData(vsd)$condition
    top_ha <- HeatmapAnnotation(
      Dose = as.character(conditions),
      col  = list(Dose = dose_palette_shared),
      show_annotation_name = FALSE,
      show_legend          = FALSE
    )

    right_ha <- rowAnnotation(
      id      = anno_text(labels_display, gp = gpar(fontsize = 7)),
      Pathway = pathway_factor,
      gap     = unit(4, "mm"),
      col     = list(Pathway = pw_palette),
      show_annotation_name = FALSE,
      show_legend          = c(id = FALSE, Pathway = FALSE)
    )

    ht_pathway <- Heatmap(
      mat_pathway,
      name              = "log2FC",
      col               = col_fun,
      row_split         = pathway_factor,
      row_title_side    = "right",
      row_title_rot     = 0,
      row_title_gp      = gpar(fontsize = 8, fontface = "bold"),
      row_gap           = unit(0, "mm"),
      cluster_rows      = FALSE,
      cluster_row_slices = FALSE,
      cluster_columns   = FALSE,
      column_split      = factor(as.character(conditions), levels = unique(as.character(conditions))),
      column_title_gp   = gpar(fontsize = 9, fontface = "bold"),
      column_title_rot  = 0,
      column_gap        = unit(0, "mm"),
      top_annotation    = top_ha,
      right_annotation  = right_ha,
      show_row_names    = FALSE,
      show_column_names = TRUE,
      column_names_rot  = 45,
      column_names_gp   = gpar(fontsize = 10),
      use_raster        = FALSE,
      height            = unit(nrow(mat_pathway) * 6, "mm"),
      width             = unit(ncol(mat_pathway) * 10, "mm"),
      heatmap_legend_param = list(
        title          = "log2(FC)",
        title_position = "leftcenter-rot",
        at             = c(-2, -1, 0, 1, 2),
        labels         = c("-2", "-1", "0", "1", "2"),
        direction      = "vertical",
        legend_height  = unit(4, "cm")
      )
    )

    px_per_mm    <- 150 / 25.4
    mm_legend    <- 0
    mm_title     <- 22
    mm_col_title <- 12
    mm_dose_bar  <- 8
    mm_col_names <- 40
    mm_padding   <- 5
    mm_rows      <- nrow(mat_pathway) * 6
    canvas_h_px  <- round((mm_legend + mm_title + mm_col_title + mm_dose_bar + mm_col_names + mm_padding + mm_rows) * px_per_mm)

    png("../results/figures/04_heatmap_pathway_genes.png",
        width = 1280, height = canvas_h_px, res = 150)
    ht_opt(TITLE_PADDING = unit(c(2, 8), "mm"))
    draw(ht_pathway,
         heatmap_legend_side    = "left",
         annotation_legend_side = "top",
         merge_legend           = FALSE,
         align_heatmap_legend   = "heatmap_top",
         column_title           = "MiaPAca-2: Genes Grouped by Pathway",
         column_title_gp        = gpar(fontsize = 12, fontface = "bold"))
    decorate_annotation("Pathway", {
      grid.text("Pathway",
                x    = unit(0, "npc"),
                y    = unit(1, "npc") + unit(3, "mm"),
                just = c("left", "bottom"),
                gp   = gpar(fontsize = 9, fontface = "bold"))
    })
    dev.off()
    message("[OK] Pathway heatmap -> 04_heatmap_pathway_genes.png",
            "  (", nrow(mat_pathway), " rows x ", ncol(mat_pathway), " cols",
            "  |  ", nlevels(pathway_factor), " pathways",
            "  |  canvas: 1280x", canvas_h_px, "px)")
  }
}

# 6. Default Heatmap (Top 50 Variable) with ComplexHeatmap
top_genes_idx <- head(order(rowVars(assay(vsd)), decreasing = TRUE), 50)
mat_var       <- assay(vsd)[top_genes_idx, ]
mat_var       <- mat_var - rowMeans(mat_var)
mat_var       <- pmin(pmax(mat_var, -2), 2)

symbols_var       <- gene_map[rownames(mat_var), "SYMBOL"]
rownames(mat_var) <- ifelse(is.na(symbols_var), rownames(mat_var), symbols_var)

col_fun_var <- colorRamp2(c(-2, 0, 2), c("navy", "white", "firebrick3"))

conditions_var <- as.character(colData(vsd)$condition)
top_ha_var <- HeatmapAnnotation(
  Dose = conditions_var,
  col  = list(Dose = dose_palette_shared),
  show_annotation_name = FALSE,
  show_legend          = FALSE
)

ht_var <- Heatmap(
  mat_var,
  name              = "log2FC",
  col               = col_fun_var,
  cluster_rows      = TRUE,
  cluster_columns   = FALSE,
  column_split      = factor(conditions_var, levels = unique(conditions_var)),
  column_title_gp   = gpar(fontsize = 9, fontface = "bold"),
  column_title_rot  = 0,
  column_gap        = unit(0, "mm"),
  top_annotation    = top_ha_var,
  show_row_names    = TRUE,
  row_names_gp      = gpar(fontsize = 8),
  column_names_rot  = 45,
  column_names_gp   = gpar(fontsize = 10),
  use_raster        = FALSE,
  height            = unit(nrow(mat_var) * 6, "mm"),
  width             = unit(ncol(mat_var) * 10, "mm"),
  heatmap_legend_param = list(
    title          = "log2(FC)",
    title_position = "leftcenter-rot",
    at             = c(-2, -1, 0, 1, 2),
    labels         = c("-2", "-1", "0", "1", "2"),
    direction      = "vertical",
    legend_height  = unit(4, "cm")
  )
)

px_per_mm_v    <- 150 / 25.4
mm_title_v     <- 22
mm_col_title_v <- 12
mm_dose_bar_v  <- 8
mm_col_names_v <- 40
mm_padding_v   <- 5
mm_rows_v      <- nrow(mat_var) * 6
canvas_h_var   <- round((mm_title_v + mm_col_title_v + mm_dose_bar_v + mm_col_names_v + mm_padding_v + mm_rows_v) * px_per_mm_v)

png("../results/figures/04_heatmap_top_variable.png",
    width = 1280, height = canvas_h_var, res = 150)
ht_opt(TITLE_PADDING = unit(c(2, 8), "mm"))
draw(ht_var,
     heatmap_legend_side    = "left",
     annotation_legend_side = "top",
     merge_legend           = FALSE,
     align_heatmap_legend   = "heatmap_top",
     column_title           = "Top 50 Most Variable Genes",
     column_title_gp        = gpar(fontsize = 12, fontface = "bold"))
dev.off()
message("[OK] Top-var heatmap  -> 04_heatmap_top_variable.png",
        "  (", nrow(mat_var), " rows x ", ncol(mat_var), " cols",
        "  |  canvas: 1280x", canvas_h_var, "px)")

# 7. Hallmark NES Barplots -- individual per dose + stitched combined
message("Building Hallmark NES plots...")

# Helper: build a single NES barplot for one dose
make_nes_plot <- function(hallmark_res, dose_label) {
  hall_df <- as.data.frame(hallmark_res) %>%
    mutate(Response = ifelse(NES > 0, "Activated", "Suppressed")) %>%
    arrange(Response, ifelse(Response == "Activated", NES, -NES)) %>%
    mutate(Description = factor(Description, levels = unique(Description)))
  
  ggplot(hall_df, aes(x = NES, y = Description, fill = Response)) +
    geom_col(width = 0.75) +
    scale_fill_manual(
      values = c("Activated" = "#D62728", "Suppressed" = "#1F77B4"),
      name = "Direction"
    ) +
    facet_grid(Response ~ ., scales = "free_y", space = "free_y") +
    geom_vline(xintercept = 0, linewidth = 0.4, color = "grey30") +
    theme_bw(base_size = 11) +
    theme(
      strip.text.y = element_text(angle = -90, face = "bold"),
      strip.background = element_rect(fill = "grey88"),
      panel.grid.major.y = element_blank(),
      axis.text.y = element_text(size = 8),
      plot.title = element_text(size = 11, face = "bold", hjust = 0.5)
    ) +
    labs(
      title = dose_label,
      x = "Normalized Enrichment Score (NES)", y = NULL
    )
}

nes_plots <- list()
for (dose in names(enrichment_results_all)) {
  hallmark_res <- enrichment_results_all[[dose]]$gsea_hallmark
  if (!is.null(hallmark_res) && nrow(as.data.frame(hallmark_res)) > 0) {
    safe_name <- str_replace_all(dose, "[^a-zA-Z0-9]", "_")
    p <- make_nes_plot(hallmark_res, paste0("Hallmark NES: ", dose))
    nes_plots[[dose]] <- p
    
    # Save individual plot
    n_rows <- nrow(as.data.frame(hallmark_res))
    ggsave(
      paste0("../results/figures/04_hallmark_nes_", safe_name, ".png"),
      p, width = 10, height = max(6, n_rows * 0.38)
    )
  }
}

# Save stitched combined NES plot (side-by-side: 0.5nM | 1nM | 5nM)
if (length(nes_plots) > 1) {
  combined_nes <- wrap_plots(nes_plots, nrow = 1) +
    plot_annotation(title = "Hallmark NES: All Concentrations",
                    theme = theme(plot.title = element_text(face = "bold", hjust = 0.5)))
  ggsave("../results/figures/04_hallmark_nes_combined.png",
         combined_nes, width = 10 * length(nes_plots), height = 12)
}

# 8. GSEA Dotplots -- individual per dose + stitched combined
message("Building GSEA dotplots...")

# Collect GSEA results across all doses
gsea_combined <- map2_dfr(
  enrichment_results_all,
  names(enrichment_results_all),
  function(res, dose_name) {
    gsea_res <- res$gsea_go
    if (!is.null(gsea_res) && nrow(as.data.frame(gsea_res)) > 0) {
      as.data.frame(gsea_res) %>%
        dplyr::select(Description, NES, pvalue, p.adjust, setSize) %>%
        mutate(
          Dose = dose_name,
          Response = ifelse(NES > 0, "activated", "suppressed")
        )
    }
  }
)

# Helper: build a single GSEA dotplot for one dose
make_gsea_plot <- function(df_dose, dose_label, top_paths_wrapped) {
  df_dose <- df_dose %>%
    filter(Description %in% top_paths_wrapped) %>%
    mutate(
      Description = factor(Description, levels = rev(top_paths_wrapped)),
      Response = factor(Response, levels = c("activated", "suppressed"))
    )
  
  ggplot(df_dose, aes(x = Response, y = Description,
                      color = pvalue, size = setSize)) +
    geom_point(alpha = 0.9) +
    # Red = most significant (low pvalue), Blue = less significant (high pvalue)
    scale_color_gradient(
      low = "#D62728", high = "#1F77B4",
      name = "pvalue"
    ) +
    scale_size_continuous(name = "Count", range = c(3, 11)) +
    # Vertical divider between activated and suppressed
    geom_vline(xintercept = 1.5, color = "grey40", linewidth = 0.6) +
    theme_bw(base_size = 10) +
    theme(
      axis.text.x = element_text(size = 9),
      axis.text.y = element_text(size = 9, hjust = 1),
      strip.background = element_rect(fill = "#2F6F8E"),
      strip.text = element_text(color = "white", face = "bold", size = 11),
      panel.grid.major.x = element_blank(),
      plot.title = element_text(hjust = 0.5, face = "bold", size = 11)
    ) +
    labs(title = paste0("Enrichment GSEA: ", dose_label),
         x = NULL, y = NULL) +
    guides(
      color = guide_colorbar(order = 1, title = "pvalue"),
      size  = guide_legend(order = 2, title = "Count")
    )
}

if (!is.null(gsea_combined) && nrow(gsea_combined) > 0) {
  # Get globally consistent top pathways (union across all doses)
  top_paths <- gsea_combined %>%
    group_by(Description) %>%
    summarise(min_pval = min(pvalue)) %>%
    arrange(min_pval) %>%
    head(25) %>%
    pull(Description)
  top_paths_wrapped <- str_wrap(top_paths, width = 35)
  
  gsea_combined <- gsea_combined %>%
    mutate(Description = str_wrap(Description, width = 35))
  
  gsea_plots <- list()
  for (dose in levels(factor(gsea_combined$Dose, levels = c("0.5nM (500pM)", "1nM", "5nM")))) {
    df_dose <- gsea_combined %>% filter(Dose == dose)
    if (nrow(df_dose) > 0) {
      safe_name <- str_replace_all(dose, "[^a-zA-Z0-9]", "_")
      p <- make_gsea_plot(df_dose, dose, top_paths_wrapped)
      gsea_plots[[dose]] <- p
      
      # Save individual plot
      ggsave(
        paste0("../results/figures/04_gsea_dotplot_", safe_name, ".png"),
        p, width = 7, height = max(6, length(top_paths) * 0.45)
      )
    }
  }
  
  # Save stitched combined GSEA plot
  if (length(gsea_plots) > 1) {
    combined_gsea <- wrap_plots(gsea_plots, nrow = 1, guides = "collect") +
      plot_annotation(
        title = "GSEA: Multi-Dose Comparison",
        theme = theme(plot.title = element_text(face = "bold", hjust = 0.5))
      )
    ggsave(
      "../results/figures/04_gsea_dotplot_combined.png",
      combined_gsea,
      width = 7 * length(gsea_plots) + 2,
      height = max(8, length(top_paths) * 0.45)
    )
  }
}

message("Visualization complete. All plots saved to ../results/figures/")
